version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./src:/project
      - /data:/data
      - /data/protein/MongoDB/data:/data/db
      - /data/protein/MongoDB/logs:/data/logs
      - /data/protein/MongoDB/config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - 27017:27017
    # command: mongod --config /etc/mongo/mongod.conf